language: python

services:
  -docker
python:
  -"3.8"

before_install:
  - choco install python --version 3.8.0
  - python -m pip install --upgrade pip

env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - make deps

script:
  - make lint
  - make docker_build
  - make docker_push
  - make test_xunit
deploy:
  provider: heroku
  app: young-headland-75288
  api_key: ${HEROKU_API_KEY}
